export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_QTY = 'ADD_QTY';
export const MINUS_QTY = 'MINUS_QTY';
export const CLEAR_CART = 'CLEAR_CART';
export const LOADING = "LOADING";
export const IS_AUTHENTICATING =  "IS_AUTHENTICATING";
export const SET_AUTH_STATUS = "SET_AUTH_STATUS";
export const SET_REQUEST_STATUS = "SET_REQUEST_STATUS";

export const SIGNIN_WITH_GOOGLE = "SIGNIN_WITH_GOOGLE";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS ";
export const SIGNOUT = "SIGNOUT";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const ON_AUTHSTATE_CHANGED = "ON_AUTHSTATE_CHANGED";
export const ON_AUTHSTATE_SUCCESS = "ON_AUTHSTATE_SUCCESS";
export const ON_AUTHSTATE_FAIL = "ON_AUTHSTATE_FAIL";

